export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    VERIFY_EMAIL: '/auth/verify-email',
    RESEND_OTP: '/auth/resend-otp',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    CHANGE_PASSWORD: '/auth/change-password',
    DELETE_ACCOUNT: '/auth/delete-account',
    ME: '/auth/me',
    LOGOUT: '/auth/logout',
    LOCATION: '/auth/location',
    GOOGLE: '/auth/google',
    FACEBOOK: '/auth/facebook',
    GOOGLE_CALLBACK: '/auth/google/callback',
    FACEBOOK_CALLBACK: '/auth/facebook/callback',
    GOOGLE_MOBILE: '/auth/google/mobile',
    APPLE_MOBILE: '/auth/apple/mobile',
    INIT_PROFILE_FILL: '/auth/init-profile-fill',
  },
  USER: {
    PROFILE: '/user-profiles',
    ADDRESSES: '/user-profiles/addresses',
    PREFERENCES: '/user-profiles/preferences',
  },
  MENU: {
    GET_ALL: '/menus',
    GET_BY_ID: '/menus',
  },
  SUBSCRIPTION: {
    GET_ALL: '/subscriptions',
    GET_BY_ID: '/subscriptions',
    PURCHASE: '/subscription-purchase',
    MY_SUBSCRIPTIONS: '/my-subscriptions',
  },
  ORDERS: {
    MY_ORDERS: '/my-orders',
    GET_BY_ID: '/orders',
    SKIP: '/orders',
    CANCEL: '/orders',
  },
  REVIEWS: {
    CREATE: '/reviews',
    MY_REVIEWS: '/my-reviews',
    UPDATE: '/reviews',
    DELETE: '/reviews',
    PUBLIC_SUBSCRIPTION: '/public/subscriptions',
    PUBLIC_VENDOR: '/public/vendors',
    PUBLIC_ORDER: '/public/orders',
  },
  REFERRAL: {
    VALIDATE: '/referral/validate',
    LEADERBOARD: '/referral/leaderboard',
    GENERATE_LINK: '/referral/generate-link',
    STATS: '/referral/stats',
  },
  TRANSACTIONS: {
    MY_TRANSACTIONS: '/my-transactions',
  },
  UPLOAD: {
    FILE: '/upload-file',
  },
  MAPS: {
    AUTOCOMPLETE: '/maps/autocomplete',
    REVERSE_GEOCODE: '/maps/reverse-geocode',
    PLACE_DETAILS: '/maps/place-details',
    SESSION_TOKEN: '/maps/session-token',
    TEST_CONNECTION: '/maps/test-connection',
  },
} as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export const ERROR_MESSAGES = {
  NETWORK_ERROR: 'Please check your internet connection and try again',
  SESSION_EXPIRED: 'Your session has expired. Please login again to continue',
  INVALID_CREDENTIALS: 'The email or password you entered is incorrect. Please check and try again',
  EMAIL_EXISTS: 'An account with this email already exists. Try signing in instead',
  PHONE_EXISTS: 'This phone number is already registered. Try signing in instead',
  INVALID_OTP: 'The verification code you entered is incorrect. Please check and try again',
  OTP_EXPIRED: 'The verification code has expired. Please request a new one',
  ACCOUNT_NOT_VERIFIED: 'Please verify your account by checking your email or phone',
  GENERIC_ERROR: 'Something unexpected happened. Please try again in a moment',
} as const;